version: '3.8'

services:
  backend:
    image: praisekeyz6/trace:backend
    container_name: trace-backend
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - ai-service

  frontend:
    image: praisekeyz6/trace:frontend
    container_name: trace-frontend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - frontend.env

  ai-service:
    image: praisekeyz6/trace:ai-service
    container_name: trace-ai-service
    restart: always
    ports:
      - "8000:8000"
      - "50051:50051"
    env_file:
      - ai-service/.env