# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trace.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrace.proto\x12\x05trace\"\xa9\x01\n\x0cScoreRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12!\n\x19transaction_history_score\x18\x02 \x01(\x02\x12\x1f\n\x17platform_activity_score\x18\x03 \x01(\x02\x12 \n\x18\x63ommunity_vouching_score\x18\x04 \x01(\x02\x12\"\n\x1aprofile_completeness_score\x18\x05 \x01(\x02\"K\n\rScoreResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0eidentity_score\x18\x02 \x01(\x02\x12\x11\n\trisk_tier\x18\x03 \x01(\t\"g\n\x0cMatchRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06skills\x18\x02 \x03(\t\x12\x10\n\x08latitude\x18\x03 \x01(\x02\x12\x11\n\tlongitude\x18\x04 \x01(\x02\x12\x11\n\tlanguages\x18\x05 \x03(\t\"P\n\x12MatchedOpportunity\x12\x16\n\x0eopportunity_id\x18\x01 \x01(\t\x12\x13\n\x0bmatch_score\x18\x02 \x01(\x02\x12\r\n\x05title\x18\x03 \x01(\t\"R\n\rMatchResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x30\n\ropportunities\x18\x02 \x03(\x0b\x32\x19.trace.MatchedOpportunity2H\n\x0eScoringService\x12\x36\n\tScoreUser\x12\x13.trace.ScoreRequest\x1a\x14.trace.ScoreResponse2R\n\x0fMatchingService\x12?\n\x12MatchOpportunities\x12\x13.trace.MatchRequest\x1a\x14.trace.MatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCOREREQUEST']._serialized_start=23
  _globals['_SCOREREQUEST']._serialized_end=192
  _globals['_SCORERESPONSE']._serialized_start=194
  _globals['_SCORERESPONSE']._serialized_end=269
  _globals['_MATCHREQUEST']._serialized_start=271
  _globals['_MATCHREQUEST']._serialized_end=374
  _globals['_MATCHEDOPPORTUNITY']._serialized_start=376
  _globals['_MATCHEDOPPORTUNITY']._serialized_end=456
  _globals['_MATCHRESPONSE']._serialized_start=458
  _globals['_MATCHRESPONSE']._serialized_end=540
  _globals['_SCORINGSERVICE']._serialized_start=542
  _globals['_SCORINGSERVICE']._serialized_end=614
  _globals['_MATCHINGSERVICE']._serialized_start=616
  _globals['_MATCHINGSERVICE']._serialized_end=698
# @@protoc_insertion_point(module_scope)
